### ISSUE TITLE
Seems still super fragile

### ISSUE THREAD

**Issue by shaunstoltz** [MO-Movia/licit#18]
Tried on the last repo before it was deleted... trying to actually use this outside the toy demo.... tremendously fragile,.... this isn't ready for prime time, abandoning as unsaleable and will fall back to CZI's repo...

**Comment by MO-Movia** [comment]
Thank you for your really helpful comment - NOT. Last repo wasn't deleted - read the notes. It was renamed to licit-fork. This is same code, just removed the link. We have resolved many, many bug in the CZI code - especially on the plugin interactions, table handling, list management, etc. It is actually being used in a couple of applications - so the "tremendously fragile" seems like you may be trying to use it in a way that is currently not being tested.

There have been some wrappers that have been placed in to make it more "Angular usable" which, if you are not running in Angular, may be creating some issues, if so, would like to know that, as we want to keep this safe for both modes.  Otherwise, if there is something in the docs that are not clear on the builds, let us know that too so that we can improve on the documentation.

Perhaps you could actually provide constructive comments by elucidating on where you are having problems so that they could be addressed.  We have a responsive team working on this, and would be happy to fix any issues you have--of course, assuming that they are actual issues with the editor and not something you are doing.  Even then, we might provide suggestions.

**Comment by MO-Movia** [comment]
So, these are the bug fixes and changes/enhancements that have been made just over the last 3 months. Since you haven't added any useful/constructive information, closing this out.

Resolved the PM   table line spacing and  alignments issue
Avoided editor   crash on toolbar click after enter key press
Implemented the   image load functionality- New Image Server to upload image
New collab   server reusing base PM collab server to resolve collaboration inconsistencies
Resolved the   Errors with formidable when bundling collab server
Reorganised the   Toolbar .
Replaced   chanzuckerberg/prosemirror-tables with ProseMirror/prosemirror-tables.
Resolved the   issue on cannot reference image using fully qualified URL
Resolved the   issues with the toolbar menu state when the editor is disabled
Resolved White   space issue in FF
Split run_collab_server   into two files for build and run collab server separately
Upgraded the   prosemirror base libraries
Upgraded all   the versions of dependency to the latest version
Resolved issue   in using licit component in Firefox
Resolved    Inconsistent behavior of editor when image is missing
Bring the math   Editor functionality
Resolved the FF   related issues when using LICIT editor as a component
Property 'runtime'   added to Licit component
Made the Licit   Editor responsive to access the toolbar button in any size
Resolved Image   flickering issue
Resolve the   copy paste issues with the bullet list
Corrected a   misspelled word using browser context menu is removing the applied CAPCO and   the word
Added dynamic   plugin loading by passing the plugins via Licit Property
Brought IFrame   in the editor
Resolved all   the issues due to the upgradation of dependency versions
Implemented   Ordered list x.x.x formatting and other styling
Implemented the   different ordered list
Bring the   custom style to a drop down menu
Applied the   selected custom style and displays the active custom style in toolbar
Binding example   piece of custom style in menu item
Avoided to use   CDN repositories for many assets including fonts, and some dynamically loaded   JavaScript
Handled the   mal-formed JSON
Blocked the   feature tables inside table
Added objectID   attribute to nodes
Created   Customstyle UI- Adding popup menu and menu icon- New/Modify Dialog, design   and implement style UI for custom style edit
Updated Iframe   plugin PM Version
Restructured   fonts so that it is no more scattered
Resolved the   issue Fonts were not packed by the npm commands
PM Debug tool   property added.
Table exceeds   the canvas
Image exceeds   the canvas
Resolved Flow   validation error
Fix on   collaboration Issues
Katex & Mathquill   Fonts are now used from the node modules instead of additional copy at source   directory
